[package]
name = "x-bow-macros"
version = "0.2.0"
edition = "2021"
description = "see the x-bow crate"
license = "MPL-2.0"
repository = "https://github.com/wishawa/async_ui"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1"
quote = "1"
syn = { version = "2", features = ["full"] }
