[workspace]
members = [
	"async_ui/",
	"async_ui_web/",
	"async_ui_web_core/",
	"async_ui_web_components/",
	"async_ui_web_macros/",
	"async_ui_internal_utils/",
	"examples/web-simple-examples/",
	"examples/web-todomvc/"
]