[package]
name = "x-bow"
version = "0.1.0"
edition = "2021"
description = "State management inspired by MobX"
license = "MPL-2.0"
repository = "https://github.com/wishawa/async_ui"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
x-bow-macros = { path = "../x-bow-macros/", version = "0.1.0" }
observables = { path = "../observables/", version = "0.1.0", default-features = false }