[package]
name = "async_context"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
scoped-tls = "1.0.1"
pin-project-lite = "0.2.9"