[package]
name = "guide-project"
version = "0.1.0"
edition = "2021"


[lib]
crate-type = ["cdylib"]

[dependencies]
async_ui_web = { path = "../../async_ui_web/" }
wasm-bindgen = "0.2.87"
futures-lite = "1.13.0"

gloo-timers = { version = "0.2.6", features = ["futures"]}