[package]
name = "scoped_async_spawn"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
scoped-tls = "1.0.0"
pin-cell = "0.2.0"
pin-project-lite = "0.2.9"