[package]
name = "ordered_btree"
version = "0.1.0"
edition = "2021"
license = "MPL-2.0"
repository = "https://github.com/wishawa/async_ui"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arrayvec = "0.7.2"
qcell = "0.5.2"