[package]
name = "async_ui_internal_utils"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
smallvec = { version = "1", features = ["union", "const_generics"] }
futures-core = "0.3.28"