[package]
name = "async_ui_web"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async_ui_core = { path = "../async_ui_core/" }
async-task = "4.3.0"
waker-fn = "1.1.0"
futures = "0.3.21"

scoped-tls = "1.0.0"

wasm-bindgen = "0.2.81"

[dependencies.web-sys]
version = "0.3.58"
features = [
	'Node',
	'Window',
]