[package]
name = "async_ui_web"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
observables = { path = "../observables/" }
async_ui_core = { path = "../async_ui_core/" }
async-task = "4.3.0"
waker-fn = "1.1.0"
futures = "0.3.21"
pin-project-lite = "0.2.9"
scoped_async_spawn = { path = "../scoped_async_spawn/" }
scoped-tls = "1.0.0"
wasm-bindgen = "0.2.81"
js-sys = "0.3.59"
[dependencies.web-sys]
version = "0.3.58"
features = [
	'Node',
	'Window',
	'Document',
	'HtmlElement',
	'HtmlButtonElement',
	'HtmlSpanElement',
	'MouseEvent',
]