[package]
name = "gtk-hackernews"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hackernews = { path = "../hackernews/", features = ["gtk"] }
async_ui_gtk = { path = "../../async_ui_gtk/" }